### ISSUE TITLE
CUDA 9 Support in v0.13

### ISSUE THREAD

**Issue by AcceptanceOfficial** [private-dreamnet/dreamtime#12]
Please add a support of CUDA 9 for older NVIDIA videoboards, cause CPU rendering doesn't work good at all, causing an evil freezes of whole computer.

**Comment by deep-man-yy** [comment]
Unfortunately this could never come, at least not from me. The automatic compilation for Windows and Ubuntu in each new version is usually complicated to configure and manage, I also plan to make a compilation only for CPU, make an extra compilation for CUDA 9 will require even more time and work (and I really do not feel like doing it manually in each new version) so for now it will not be possible, if you really need a version with CUDA 9 someone else will need to compile it or someone in [Patreon with the #opensource master category](https://www.patreon.com/deepmanyy) request it. Sorry.

**Comment by wisp101** [comment]
What do you mean by support? Like an official build? Or just options in the build scripts or something to target CUDA 9?

**Comment by AcceptanceOfficial** [comment]
> 
> 
> What do you mean by support? Like an official build? Or just options in the build scripts or something to target CUDA 9?

I mean actually to make possible to process images using older CUDA and so on, older NVIDIA drivers. Last CUDA 10.1 is fully compatible, but drivers are too old to DreamTime to work. And CPU rendering, as I said earlier, works awful.

**Comment by wisp101** [comment]
It’s already possible to make a version compatible with CUDA 9 by manually managing the python dependencies and doing a custom build. What support do you expect? It’s not really feasible to maintain official builds for all platforms/CUDA versions, but the ability to change the CUDA type during a build seems pretty reasonable

**Comment by AcceptanceOfficial** [comment]
> It’s already possible to make a version compatible with CUDA 9 by manually managing the python dependencies and doing a custom build. What support do you expect? It’s not really feasible to maintain official builds for all platforms/CUDA versions, but the ability to change the CUDA type during a build seems pretty reasonable

Fresher videoboards could support older software, but not in the opposite order. So why use CUDA 10 when we can use 9?
I also could build it by myself for my own purposes, but I have an issue to get the PyTorch version compatible with CUDA 9.

**Comment by wisp101** [comment]
Newer cards don’t support CUDA 9, and supporting newer cards is more important than supporting older ones, so we will most likely only provide official builds for CUDA 10.

**Comment by AcceptanceOfficial** [comment]
Okay, and what's about PyOpenCL? It should get us rid off problems with different GPUs cause it's supported by AMD and Intel GPUs as well as on NVIDIA. CUDA could be faster, but including OpenCL to an app would be a very good choice.
I would like to make it by myself, but unfortunately, I don't know Python as well as OpenCL commands and if I even could make something, there's no fact it should work proper.

**Comment by wisp101** [comment]
OpenCL support for PyTorch, the ai library the algorithm uses, is absolute trash and not usable

**Comment by wisp101** [comment]
Closing since we will be sticking with CUDA 10 for the foreseeable future.
