### ISSUE TITLE
Manual User Interface

### ISSUE THREAD

**Issue by honkymchonkerston** [private-dreamnet/dreamtime#14]
At the basic level of implementation:

A "draw in feature" what I mean by that is, perhaps the user could help mark the targets for the ai to better understand the area you want to target, this could help improve results until the algo itself is improved, so for example you could have "auto" mode which is what the program has now which is that it tries to render to the best of its ability what it thinks are the targets, or you could either a) manually draw in or b) using a selection tool set to pick the areas you want to transform.

As an example you could have a tool to mark the nipples, the outline of the breast, or the lower regions front or back. This might help clear some hurdles as far as how close the distance is, if there are any obstructions, or help mark the check points like where the belly button is since I read (I believe) that is one of the areas it uses to detect removal of clothing. With a manual adjustment system. You could have different markers with different labels and drag and drop them and resize them to the relative area or draw them manually. These types of tools are used a lot when you use custom faces for games and things. 

I just thought it might be a way to improve the quality of the tool until it is at a point where it is better understood and can do more diverse angles, shapes, and sizes by itself. Even if the auto mode was substantially improved manually highlighting things and sectioning off things as described would still come in handy for specific situations regardless. Plus the human eye can see things that sometimes an AI can't and manually marking them will help in that regard. 

At a more advanced level of integration:

This would be on the more advanced scale after the initial tools were created but since each area could be manually selected theoretically you could choose relative skin tones with a dropper, nipple size, lighting, and other things to help the results blend with the original picture. Just some thoughts on what the benefits could be further down the line if you build this type of system from the early onset.

Apologies if this explanation is at any point disjointed, I copy, pasted, and edited from the discord these ideas I had and at request posted here to keep it visible. 

As an addendum:

This is just some more spit balling from the discord that might help illustrate it in terms of the process that would occur theoretically:

"you can imagine running phase 1, show the image with the mask in GUI and allow user to adjust.
have the adjusted as input to phase II show the image with masks in GUI again and allow user to adjust.
have the adjusted input as phase III

We can take the adjustments and use to train the algo on.. so it does it's job better at phase I and II...

it would solve issues like cyclops boobs and stuff bouncing around ... phase I & II are responsible for those issues"

deeppppp

**Comment by honkymchonkerston** [comment]
This is just some more spit balling from the discord that might help illustrate it in terms of the process that would occur theoretically:

"you can imagine running phase 1, show the image with the mask in GUI and allow user to adjust.
have the adjusted as input to phase II show the image with masks in GUI again and allow user to adjust.
have the adjusted input as phase III

We can take the adjustments and use to train the algo on.. so it does it's job better at phase I and II...

it would solve issues like cyclops boobs and stuff bouncing around ... phase I & II are responsible for those issues"

- deeppppp

**Comment by gastyroma** [comment]
Eymi user at the Discord channel shared his linux version (ithout checkpoints, without dependancy) with personalization settings:
"with/without/extra hair and aur/tit size modification and multi-people test (disable filterCouple)"
https://cdn.discordapp.com/attachments/598277860309991458/601808217575653379/deep-modified.rar
