### ISSUE TITLE
In GUI Result Image saves without proper png extension

### ISSUE THREAD

**Issue by honkymchonkerston** [private-dreamnet/dreamtime#15]
In the save prompt window .png has to be typed in manually after file name saving in windows 10 or it saves as a file without an extension, when you go to save the file type is under "all files" and not png. 

This isn't a major issue but a mild annoyance, not sure if it's the same using cli as it is in gui or if this is because I don't have extensions on but either way saving as a png automatically would be ideal since that is the proper file extension for the image.

**Comment by wisp101** [comment]
I think we need to switch from download.js to exposing an api through deepTools. I believe [this](https://electronjs.org/docs/api/dialog) is the relevant documentation.
