### ISSUE TITLE
Put Mac Compatibility Status on Readme

### ISSUE THREAD

**Issue by DiMiTriFrog** [private-dreamnet/dreamtime#19]
When dreamtime compatible with macOS? :(

**Comment by wisp101** [comment]
Its already supported. While official builds have not been provided yet, you can build it yourself. If you get on discord, people can help you do it.

**Comment by StrattonPau** [comment]
Okey, I go to discord.

**Comment by helloooo1132** [comment]
Where I can find this versions for mac?
Link?

**Comment by wisp101** [comment]
We don't provide Mac builds, so you need to build this project yourself

**Comment by deeppppp** [comment]
While DreamTime, does not have a build for MacOS available, the command line tool that powers DreamTime, does:
https://github.com/private-dreamnet/dreampower/releases

So you won't have a nice user interface, but you can use the Terminal to process images.
