### ISSUE TITLE
Copy Result by Right Clicking

### ISSUE THREAD

**Issue by wisp101** [private-dreamnet/dreamtime#29]
Copied from the last issue tracker. Basically, since electron lacks chrome's context menus, users can't right click to copy/save images. I worked on fixing that using electron's [nativeImage api](https://electronjs.org/docs/api/native-image), but i stopped because I couldn't make a way to satisfactorily tell the user that an image was copied.

**Comment by kolessios** [comment]
I think that for now we will settle for a simple "Save As..." option, if in the future something more advanced is required (for some reason (¬_¬ )) please reopen the Issue.
