### ISSUE TITLE
QOL: setup.ps1 / requirements-[OS].txt has pyTorch wheel for Python 3.6 

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#31]
setup.ps1 / requirements-[OS].txt has pyTorch wheel for Python 3.6 

"https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-win_amd64.whl"
causing a failure when the user has a different Python version than v3.6 - like current stable build 3.7

can we change this out so that the pyTorch for the users Python version is grabbed and installed instead?

**Comment by wisp101** [comment]
Moved this to DreamPower: https://github.com/private-dreamnet/dreampower/issues/3
