### ISSUE TITLE
GUI result image is white rectangle only

### ISSUE THREAD

**Issue by Wizradus** [private-dreamnet/dreamtime#32]
Hello.
When I tested your app, it produced only empty white image. After save attempt is created file only with size 1kb, which is containing word "undefined". Version 0.1.2.
OS Windows 10 64b, used GeForce GTX 1050 Ti and also CPU for rendering.

**Comment by olskar** [comment]
Same error

**Comment by kolessios** [comment]
This is probably caused by the library we used to save the photos. In version 1.0.0 another method will be used that should work.
