### ISSUE TITLE
GPU option by name not shown on linux at [Process Device] page while nvidia card is present.

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#33]
GPU option by name not shown on linux at [Process Device] page while nvidia card is present.
When using the Custom GPU ID, the CLI will use nvidia card correctly.

Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 4.19.0-5-amd64Architecture: x86-64
i7 3930k @ 4.6Ghz

Is the GPU name property not available on linux?

**Comment by deep-man-yy** [comment]
That functionality comes from [gpu-info](https://github.com/FallingSnow/gpu-info), the only package that offers that but its author has discontinued and only has Windows support.

If anyone knows how to get the information on other operating systems (better if is a gpu-info fork) please let me know.

**Comment by wisp101** [comment]
I can probably get it from the cli. I'll work on that when i get the time
