### ISSUE TITLE
QOL: 2nd cropping step

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#36]
from jesscold:

feature request: in the cropper tool, give the ability to have another 'cropping' step where you draw a box around the "object" you are interested in. The tool would then crop that out and pass to CLI (padding it to make 512x512) at the end, it would crop out the same coords from the result and overlay on the original. this way we can easily work with images containing multiple people

actually  a lasso tool would be better

**Comment by sTiKyt** [comment]
Is that supposed to be closed?
