### ISSUE TITLE
Transformation #1 Failed

### ISSUE THREAD

**Issue by lordkronox** [private-dreamnet/dreamtime#46]
Trying to run in windows 10 but without success.

Updated windows and all drivers, and tried using both cpu and gpu and reinstalling.

The error I get is

```
Transformation #1 failed
The process has been interrupted by an error. This can be caused by:

- A corrupt installation
- Insufficient RAM. Buy more RAM! (8 GB recommended)
- If you are using GPU: The graphics card was not found, it is not compatible (minimum: 3.5 CUDA compute capability) or the drivers are outdated.
- Check the console for more information.


For help, please report the following to one of our developers:

https://rollbar.com/occurrence/uuid/?uuid=cfe7433d-6aca-4685-df94-111ed6e203c3
```

**Comment by kolessios** [comment]
It seems that DreamPower generates an error but without giving more information that can help us find the origin. Could you give more details about what happens? What type of photo are you trying to process (png, jpg), the size of the photo, the exact text that appears on the console (the text in red), preferences and any detailed information you can give.

**Comment by lordkronox** [comment]
@kolessios At the first time, it generated an invisible image, that I save but doesn't appear in file explorer. After the first try, all the subsequent runs fail.

The text in red is just "FAIL!", and the run log is
```
Executing phase: correct_to_mask
Executing phase: dress_to_correct
GPU IDs: [0]
Executing phase: correct_to_mask
Executing phase: dress_to_correct
GPU IDs: [0]
Executing phase: correct_to_mask
Executing phase: dress_to_correct
GPU IDs: [0]
```

I've tried to find more logs in the program folder, but with no success.

I've tried both png and jpg photos, and with a 512x512 or cropped one, all fail after the first try.
This happens with CPU or GPU, and I've tried already to run as administrator, reinstall, manual download the checkpoints and installing in another folder.

I don't know if it can help or not, but I have an old version of deepnude source, that works fine using python to run the script, even with the dreamtime checkpoints.

**Comment by kolessios** [comment]
It seems a very special error, thanks for the information we will try to see what could cause it. Additionally could you try an earlier version? For example [0.1.2](https://github.com/private-dreamnet/dreamtime/releases/tag/0.1.2) and tell me if it works for you.

**Comment by deeppppp** [comment]
@lordkronox 
is there a folder called 'checkpoints' inside the 'cli' folder in the folder where DreamTime was installed?

for example if you installed v1.0.0 with the default install path:
C:\Program Files\Iván Bravo Bravo\DreamTime\cli\checkpoints

and if the 'checkpoints' folder is there, does it contain these files:
cm.lib
mm.lib
mn.lib

**Comment by deeppppp** [comment]
@lordkronox 
could you also run just dreampower.exe via the following instructions, and report back any errors that are printed on the screen?

-- you can find the 'cli' folder in the DreamTime folder;  if you installed v1.0.0 with the default install path: C:\Program Files\Iván Bravo Bravo\DreamTime\cli\

1) place a 512x512 pixel image in the 'cli' folder
2) click the windows START button
3) type in 'run' [ENTER]
4) type in 'cmd' [ENTER]
5) type in
cd "\Program Files\Iván Bravo Bravo\DreamTime\cli"
[ENTER]
(or the path you installed DreamTime in)
6) type in 
dreampower.exe -i <your input image file name with extension> -o test2_out.png --gpu 0
[ENTER]
(for example: dreampower.exe -i test2.jpg -o test2_out.png --gpu 0)

report back any errors...

Thanks !

**Comment by haotian0430** [comment]
> 这似乎是一个非常特殊的错误，感谢我们将尝试查看可能导致它的信息。另外你可以试试早期版本吗？例如[0.1.2](https://github.com/private-dreamnet/dreamtime/releases/tag/0.1.2)并告诉我它是否适合你。


My question is the same as his question. The picture is converted to cpu and is an invisible picture and cannot be saved.

**Comment by peepeepoopoo83** [comment]
> @kolessios At the first time, it generated an invisible image, that I save but doesn't appear in file explorer. After the first try, all the subsequent runs fail.
> 
> The text in red is just "FAIL!", and the run log is
> 
> ```
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> ```
> 
> I've tried to find more logs in the program folder, but with no success.
> 
> I've tried both png and jpg photos, and with a 512x512 or cropped one, all fail after the first try.
> This happens with CPU or GPU, and I've tried already to run as administrator, reinstall, manual download the checkpoints and installing in another folder.
> 
> I don't know if it can help or not, but I have an old version of deepnude source, that works fine using python to run the script, even with the dreamtime checkpoints.
> 
> I'm using Windows 10 rev 1809, intel cpu, a GTX 1080 and have the updated NVIDIA drivers.
> 
> Is there any more information that I can provide?



> @kolessios At the first time, it generated an invisible image, that I save but doesn't appear in file explorer. After the first try, all the subsequent runs fail.
> 
> The text in red is just "FAIL!", and the run log is
> 
> ```
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> ```
> 
> I've tried to find more logs in the program folder, but with no success.
> 
> I've tried both png and jpg photos, and with a 512x512 or cropped one, all fail after the first try.
> This happens with CPU or GPU, and I've tried already to run as administrator, reinstall, manual download the checkpoints and installing in another folder.
> 
> I don't know if it can help or not, but I have an old version of deepnude source, that works fine using python to run the script, even with the dreamtime checkpoints.
> 
> I'm using Windows 10 rev 1809, intel cpu, a GTX 1080 and have the updated NVIDIA drivers.
> 
> Is there any more information that I can provide?

I have the same exact problem, it shows me the error when using GPU and if I use CPU the result is "invisible" and when saved it doesn't show up in the explorer
