### ISSUE TITLE
After install Release 1.0.0 nothing happens. (win7)

### ISSUE THREAD

**Issue by Marechal17** [private-dreamnet/dreamtime#49]
After install Release 1.0.0 nothing happens. (win7) The program use 47k memories but I don't see the apps.

**Comment by deeppppp** [comment]
Same for user @oshitlmao
Windows 10 - multiple monitor setup (but also happens with single monitor)
App shows in task manager, but not on the task bar as 'running app' and the app window does not show.
previous DreamTime version works OK.

**Comment by kolessios** [comment]
It is possible that some important task is not starting correctly. Could you start the program using the console and send a screenshot of what appears? You can do it this way:

- Open the folder where DreamTime is installed.
- Press SHIFT and without releasing it right click on some white space in the folder, the option "Open Powershell window here" should appear.
- A console will open, type:  `.\DreamTime.exe`
- Press ENTER

**Comment by Marechal17** [comment]
![screenshot](https://user-images.githubusercontent.com/53652826/62969055-b231bd80-be0c-11e9-93a4-55df02f3ff6a.jpg)

**Comment by Marechal17** [comment]
![screenshot](https://user-images.githubusercontent.com/53652826/62969141-e73e1000-be0c-11e9-897c-775429b94515.jpg)

**Comment by Marechal17** [comment]
![screenshot](https://user-images.githubusercontent.com/53652826/62970755-7698f280-be10-11e9-9959-9d9d2b99c39a.jpg)

**Comment by kolessios** [comment]
Another user has reported the same problem, apparently in his case they managed to solve it by correcting the PATH, he did not give more details so he can refer to moving the DreamTime installation or by manually checking any problem that exists in the Windows `PATH` variable, also they mention having executed the `sfc /scannow` command to correct problems in Windows installation.

In summary, it seems that some file or configuration in your operating system may be causing the problem.

**Comment by Marechal17** [comment]
i do sfc /scannow on C:\Windows\System32 nothing found.
