### ISSUE TITLE
RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#5]
seems related to:
https://github.com/pytorch/pytorch/issues/16559

solutions:
"Pre-initializing CUDA in the main thread mitigates the issue"

avoid issue:
"if you try to create a CUDA tensor in a thread it produces this error"

**Comment by PommeDroid** [comment]
Is this bug occured only when using the --gif option ?

**Comment by deeppppp** [comment]
yes, during the --gif option for CLI.

**Comment by deep-man-yy** [comment]
Fixed in v0.1.2
