### ISSUE TITLE
v1.0.0-Convert picture error display save link

### ISSUE THREAD

**Issue by haotian0430** [private-dreamnet/dreamtime#55]
The converted image is displayed as a blank image and cannot be saved locally. Even if you save it locally, it's a link shortcut.

**Comment by kolessios** [comment]
v1.1.0 shows an error message if it detects that the photo has not been saved correctly by DreamPower. It is not a fix, but it should no longer show an empty photo, I need more information about the problem since it occurs under specific conditions and we still don't know why.
