### ISSUE TITLE
Transformation #1 failed - python 

### ISSUE THREAD

**Issue by juanjavito** [private-dreamnet/dreamtime#57]
python: can't open file 'main.py': [Errno 2] No such file or directory

**Comment by Madness75** [comment]
i have the same problem

**Comment by kolessios** [comment]
The error indicates that the DreamPower Python script could not be found for the transformation, this "script" is intended for developers so if you are not trying to run the program in developer mode then go to the **Settings** and deactivate the option **Use Python**
