### ISSUE TITLE
app-builder-bin-2.7.1.tgz: unexpected end of file

### ISSUE THREAD

**Issue by vudefive** [private-dreamnet/dreamtime#58]
Hello!
I've got an error on the second stage of "yarn install"

error An unexpected error occurred: "https://dreamnet.tech:4873/app-builder-bin/-/app-builder-bin-2.7.1.tgz: unexpected end of file

**Comment by kolessios** [comment]
The error indicates that there was a problem downloading the file from one of the libraries we use. Try again, if it continues to fail delete the yarn cache or try to use a VPN.
