### ISSUE TITLE
Windows 10 Pro X64 not 'N' version Media Pack detection

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#59]
Windows 10 Pro X64 not 'N' version Media Pack detection fails, because the 
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\WindowsFeatures\WindowsMediaVersion
is not present, had 2 users experience this issue; both on Windows 10 Pro.
a [Find] in the registry editor did not return a location for any key with 'WindowsMediaVersion'
while the Windows Media features are on the OS.

HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup
was not present, maybe this has to do with the way Windows 10 was installed?

**Comment by fmohican** [comment]
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup`
The `Setup` Folder doesn't have any subfolder called "WindowsFeatures" or "WindowsMediaVersion"

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
```

**Comment by fmohican** [comment]
I just add the missing registry, isn't a "real fix" but will make ("cheat") dreamtime work.

Just unzip and double click 👍 
VT: https://www.virustotal.com/gui/file-analysis/ZmQyMzkyMDQwYTU2ZDBkNjIwZDYyMzhjMzk1NTRjN2M6MTU2NjE0MjE5NA==/detection
[QuickFix.zip](https://github.com/private-dreamnet/dreamtime/files/3513195/QuickFix.zip)

**Comment by kolessios** [comment]
v1.1.0 remove that not complying with the requirement restricts the use of the program. It is not exactly a fix but it will work for now.

**Comment by kolessios** [comment]
If someone knows why the path in the registry does not exist on some devices and knows how to fix this bug properly, your help will be greatly appreciated.
