### ISSUE TITLE
App thinks we are offline

### ISSUE THREAD

**Issue by PommeDroid** [private-dreamnet/dreamtime#60]
**Describe the bug**
The app thinks we are offline.
Probable cause of the problem : the .env is present but not loads on time or not at all by the app -> the app have no Nucleus id -> it fails to checks the remote nucleus api -> the app thinks we are offline.

**To Reproduce**
Starting the app go to the about page but it happen randomly.

**Environment :**
 - Version 1.1.0
 - OS: Ubuntu 18/16, ArchLinux, MacOs
 - Report URL: Down

**Comment by kolessios** [comment]
Version 1.1.0 uses an update from a library that solves that problem. Try deleting the `node_modules` folder and the `yarn.lock` file and reinstall everything with `yarn install`

**Comment by PommeDroid** [comment]
Yeah seem like it's not happening anymore with all the libs updated in the new version. Closing.
