### ISSUE TITLE
2 Feature request

### ISSUE THREAD

**Issue by kall666** [private-dreamnet/dreamtime#65]
Hello

1.
I hear this one no need 512x512
https://github.com/zhengyima/DeepNude_NoWatermark_withModel
he said input size = output size. please take a look to check :)

2.
please change "every run +0.2" to "every run +0.1" or let user input the value

thankyou verymuch :))

**Comment by deeppppp** [comment]
while the repository you mentioned allows any input size and returns the same size for the output;, the checkpoints are only for 512x512 images. Processing any other size with the checkpoints will result in bad quality outcomes.
