### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tangcan1600** [private-dreamnet/dreamtime#66]
The process has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.
> 'main.py': [Errno 2] No such file or directory
> (null): can't open file
> (null): can't open file 'main.py': [Errno 2] No such file or directory

**Comment by kolessios** [comment]
Please use the [bug report](https://github.com/private-dreamnet/dreamtime/issues/new?assignees=&labels=bug&template=bug_report.md&title=) template.
