### ISSUE TITLE
Freezing down whole PC after a minute of processing

### ISSUE THREAD

**Issue by AcceptanceOfficial** [private-dreamnet/dreamtime#67]
When I run the DreamTime on Windows 10 Home x64 (licensed), it freezes down whole computer after a minute of processing.

And it also worked well on Kali Linux 2018 (Debian Wheezy) on the same PC, yes, it took out 2,5 minutes to process, but the app did it.

Specifications are:
Intel Celeron N3350
4Gb DDR3L RAM

**Comment by AcceptanceOfficial** [comment]
Also same bug on AMD Athlon II x4 620 with same amount of RAM.

**Comment by kolessios** [comment]
Please use the [bug report](https://github.com/private-dreamnet/dreamtime/issues/new?assignees=&labels=bug&template=bug_report.md&title=) template.
