### ISSUE TITLE
DreamPower version confusion

### ISSUE THREAD

**Issue by quetzalsly** [private-dreamnet/dreamtime#76]
DreamTime comes with version 0.0.1 of DreamPower? I thought something was wrong so I downloaded DreamPower separatly (the 1.1.0 version). After changing folder in settings and restarting the app, it also updated that version to 0.0.1. Except comparing the folders, they are completly different, they have different DLL's, different python versions etc.

Which is the latest version? Does DreamTime always come with the latest version or no?

**Comment by kolessios** [comment]
Sorry for the confusion, but what you are downloading is not DreamPower, DreamPower is already included with DreamTime, what you are downloading is v0.0.1 of the Checkpoints (the models used by DreamPower to transform the photos).

DreamTime v1.1.0 comes with DreamPower v1.0.0, updating DreamPower will cause DreamTime to stop working properly.
