### ISSUE TITLE
Diacritic letters in the filename generate white image

### ISSUE THREAD

**Issue by PommeDroid** [private-dreamnet/dreamtime#8]
Nudify an image that contains diacritic letters in the filename (in the name of the file, such as ž or ý) it will generate just white image.

**Comment by wisp101** [comment]
I don't think OpenCV supports files with unicode names. I'll try to look for a way to get past that. Worst comes to worst, I think we need to implement out own image loader and use `imdecode` to get the mat for processing.

**Comment by Gelu1992** [comment]
First version was woking fine with this file-names, I experienced it just in this release.
