### ISSUE TITLE
latest release .deb fails to install using dpkg

### ISSUE THREAD

**Issue by qazsedcftgbhujmkol** [private-dreamnet/dreamtime#81]
**Describe the bug**
dpkg reports that the .deb file from the 1.1.0 release page is `not a Debian format archive`

**To Reproduce**
1. download the linux install file from https://github.com/private-dreamnet/dreamtime/releases/tag/v1.1.0
2. use dpkg to install it (sudo dpkg -i <file>)

**Expected behavior**
Dreamtime should successfully install.

**Enviroment (please complete the following information):**
 - OS: Ubuntu 19.04 (Installed 4 hours ago)

**Additional context**
Full console log with dpkg set to the maximum log value:

> primary@741852963:~/Desktop$ sudo dpkg --debug=73773 -i DreamTime-v1.1.0-ubuntu-x64.deb 
D000001: ensure_diversions: new, (re)loading
D000001: ensure_statoverrides: new, (re)loading
D000010: path_remove_tree '/var/lib/dpkg/tmp.ci'
D000010: path_remove_tree running rm -rf '/var/lib/dpkg/tmp.ci'
dpkg-deb: error: 'DreamTime-v1.1.0-ubuntu-x64.deb' is not a Debian format archive
dpkg: error processing archive DreamTime-v1.1.0-ubuntu-x64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
D000010: path_remove_tree '/var/lib/dpkg/tmp.ci'
D000010: path_remove_tree '/var/lib/dpkg/reassemble.deb'
D010000: trigproc_run_deferred
Errors were encountered while processing:
 DreamTime-v1.1.0-ubuntu-x64.deb

[edit]
To clarify:
I downloaded both using wget (I downloaded the cdn-hosted cpy after the github-hosted one failed)
The cdn-hosted copy installs correctly.
It's just the github-hosted copy that seems to have an issue.

**Comment by qazsedcftgbhujmkol** [comment]
To clarify:
I downloaded both using wget (I downloaded the cdn-hosted cpy after the github-hosted one failed)
The cdn-hosted copy installs correctly.
It's just the github-hosted copy that seems to have an issue.

**Comment by kolessios** [comment]
For some reason certain Internet connections have problems downloading Github files, it is possible that this error is caused by downloading a corrupt file. If that is the reason then there is not much we can do, luckily we have the CDN.
