### ISSUE TITLE
in-program checkpoints download not working correctly

### ISSUE THREAD

**Issue by qazsedcftgbhujmkol** [private-dreamnet/dreamtime#82]
**Describe the bug**
I used the built-in download (the update button).
It went from 99.99% to 100.00% then to 50.00% over the course of about 2 seconds.
The cancel button doesn't work in this state either.

update:
I tried closing and re-opening the program,then clicking update again.
The progress goes straight to 50% and it gave me a second error link (see below)

**To Reproduce**
1. Install and open dreamtime on ubuntu 19.04
2. scroll down to the checkpoints download section
3. click update
4. wait until the end,where it will break.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53264121/64862070-84b57b00-d629-11e9-86df-6759da29127c.png)

**Enviroment (please complete the following information):**
 - Version 1.1.0
 - OS: Ubuntu 19.04
 - Report URL: https://rollbar.com/occurrence/uuid/?uuid=366903d6-5f14-4770-a269-46e8a0686b2d
second report url : https://rollbar.com/occurrence/uuid/?uuid=f61832b6-e10a-4b6d-b88b-10e8d22aa834

**Comment by kolessios** [comment]
I will try to reproduce this problem, however I recommend deleting the `v0.0.1.zip` file from your Downloads folder, it may be corrupt and DreamTime may not be able to decompress it.
