### ISSUE TITLE
freezing after 1 minute

### ISSUE THREAD

**Issue by liauwliauw6** [private-dreamnet/dreamtime#83]
Freezing happens after 1 minute of processing.

i run with cpu and after 1 min of processing it freezes the computer, cant move the mouse , cant press the keyboard.

im running on
 - Version 1.1.0
 - OS: Windows 10 Home Single language 1803 x64
-Intel core i3-7020 Cpu 2.30 ghz
- 4 gb installed

**Comment by kolessios** [comment]
It seems to me that your PC does not have the power to run DreamTime. It is recommended a more powerful CPU and at least 8 GB of RAM, **however** it is also true that in theory other people have managed to run DreamTime on a less powerful processor, so for now the only thing I can recommend is that you close all the possible programs before using DreamTime.

**Comment by liauwliauw6** [comment]
thank you for your response :)
