### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by amanmouth** [private-dreamnet/dreamtime#84]
It says there is a problem loading the necessary dreamwork file and that the installation might be corrupt.

Using the Mac version 1.10

https://rollbar.com/occurrence/uuid/?uuid=f2ab925f-69bc-4b63-8f2d-a19a1176950f

> [17432] Error loading Python lib '/Applications/DreamTime.app/Contents/MacOS/cli/Python': dlopen: dlopen(/Applications/DreamTime.app/Contents/MacOS/cli/Python, 10): Symbol not found: _clock_getres Referenced from: /Applications/DreamTime.app/Contents/MacOS/cli/Python Expected in: /usr/lib/libSystem.B.dylib in /Applications/DreamTime.app/Contents/MacOS/cli/Python
> [17431] Error loading Python lib '/Applications/DreamTime.app/Contents/MacOS/cli/Python': dlopen: dlopen(/Applications/DreamTime.app/Contents/MacOS/cli/Python, 10): Symbol not found: _clock_getres Referenced from: /Applications/DreamTime.app/Contents/MacOS/cli/Python Expected in: /usr/lib/libSystem.B.dylib in /Applications/DreamTime.app/Contents/MacOS/cli/Python

**Comment by kolessios** [comment]
Thanks for the report, as the error message indicates, your operating system has problems trying to open/execute files that are necessary by the transformation algorithm. I will try to reproduce the problem but I need you to provide me with the version of macOS you are using. 

For now, the only thing I can recommend is that you try to install any macOS update you can.

**Comment by amanmouth** [comment]
My macOS is El Capitan version 10.11.6

**Comment by kolessios** [comment]
In the chat it has been discovered that apparently DreamTime needs macOS **10.13 High Sierra** or higher to work.
