### ISSUE TITLE
Extremely ugly results

### ISSUE THREAD

**Issue by RighteousGit** [private-dreamnet/dreamtime#86]
Hi! I tried with +10 different pics in the result never was acceptable in any way. The program never detected the right silhouette and it's so far away to being usable. I will never use DreamTime untill it improves drastically. It's a waste of time. Please still fixing it. Thanks in advance.

**Comment by kolessios** [comment]
Thanks but this is not a valid Issue.

**Comment by thvozdovic** [comment]
@kolessios could there be some kind of tool that would allow to select where the parts of the body are to help the ai ? (sorry for my english if i wrote something wrong
)
