### ISSUE TITLE
Not sure what to make of it

### ISSUE THREAD

**Issue by Marridreg** [private-dreamnet/dreamtime#89]
Noting seems wrong, so not sure what the bug is,  was told to report it to you guys though, an error window popped up first thing after opening the program and clicking "I understand".

**To Reproduce**
1. Open the program
2. Click on the "I understand" link
3. Error pops up.

**Screenshots**
![image](https://user-images.githubusercontent.com/42444570/65356259-01180300-dbc2-11e9-8e4b-f10509ab04f1.png)

**Enviroment (please complete the following information):**
 - Version [e.g. 1.1.0]
 - OS: [e.g. Windows 10.0.17763 Build 17763]
 - Report URL: [https://rollbar.com/occurrence/uuid/?uuid=767ca1f8-35be-4a53-d09e-6ed0dead5758]

**Comment by medalawi** [comment]
same problem here windows 10 1903

**Comment by jesscold** [comment]
you're missing checkpoints. also windows sucks

**Comment by swaggyP36000** [comment]
How do I get said checkpoints?

**Comment by kolessios** [comment]
Thank you but we already knew about this problem and it is harmless, it only occurs when you start DreamTime for the first time.
