### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by 1fkdldjs** [private-dreamnet/dreamtime#92]
DreamPower has reported that the photo has been transformed but the file does not exist! This may be due to a problem saving the photo, verify that DreamPower has write permissions and that your Antivirus is not detecting false positives. It is also possible that DreamPower is ending abruptly due to a major problem.

How I can solve this problem?

**Screenshots**
![asz](https://user-images.githubusercontent.com/55593108/65365042-0c663f80-dc51-11e9-9de6-410b447705cd.png)

**Enviroment (please complete the following information):**
 - Version [e.g. 1.1.0]
 - OS: [e.g. Windows 10 home]

**Comment by kolessios** [comment]
This problem usually happens when you install DreamTime in a place with spaces or special characters (it happens often on operating systems with a language other than English). Try installing DreamTime again but in the installation select some other folder.
