### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by lfrezza** [private-dreamnet/dreamtime#98]
Hi,
when I try to use Dreamtime (on OS Sierra 10.12.6) the answer is always:

Transformation #1 failed
There was a problem loading a necessary DreamPower file. It is possible that your installation is corrupt, download the program again and reinstall.

For more information please report the following URL on Github or here: https://rollbar.com/occurrence/uuid/?uuid=398e79cc-7cb5-4793-c0d2-335cd2a12f9e

Thanks

**Expected behavior**

**Screenshots**

**Enviroment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - OS: [e.g. Windows 10 1803]
 - Report URL: [If applicable, e.g. https://rollbar.com/occurrence/...]

**Additional context**

**Comment by kolessios** [comment]
Greetings, we have recently discovered that DreamTime needs macOS **10.13 High Sierra** or higher to work. So please update your operating system if you want to use DreamTime.

**Comment by lfrezza** [comment]
Thanks
